### ISSUE TITLE
MPGS's reference ID issue in Opencart

### ISSUE THREAD

**Issue by foreigntalent** [marcoblos/mastercard-mpgs-sdk#2]
Dear Sir,

We are having some issues with connecting to our bank's MPGS services and hope to clear this:

The issue we are encountering right lies with calling the reference id inside the php file:

session_unset();
session_start();

include "api_lib.php";
include "configuration.php";
include "connection.php";

//Ensure this is the first invokation of this page
if($_SERVER['REQUEST_METHOD'] == "POST")
{

	if (array_key_exists("submit", $_POST))
  unset($_POST["submit"]);
	
$order_amount = $_POST["order_amount"];   
$order_currency = $_POST["order_currency"];
$customer_receipt_email = "'" . $_POST["customer_receipt_email"] . "'";

//Creates the Merchant Object from config. If you are using multiple merchant ID's, 
	// you can pass in another configArray each time, instead of using the one from configuration.php
$merchantObj = new Merchant($configArray);

  // The Parser object is used to process the response from the gateway and handle the connections
  // and uses connection.php
  $parserObj = new Parser($merchantObj);

//The Gateway URL can be set by using the following function, or the 
//value can be set in configuration.php
//$merchantObj->SetGatewayUrl("https://xxx.xxx.xx.com/api/nvp");	
  $requestUrl = $parserObj->FormRequestUrl($merchantObj);

  //This is a library if useful functions
  $new_api_lib = new api_lib;

	//Use a method to create a unique Order ID. Store this for later use in the receipt page or receipt function.
$order_id = $new_api_lib->getRandomString(10);  
**$order_reference = $new_api_lib->getRandomString(10)**;  
		
//Form the array to obtain the checkout session ID.									 
	$request_assoc_array = array("apiOperation"=>"CREATE_CHECKOUT_SESSION",
													 	   "order.id"=>$order_id,
													 	   "order.amount"=>$order_amount,
													     "order.currency"=>$order_currency,
														 "order.reference"=>$order_reference
													 		);
													 		
	//This builds the request adding in the merchant name, api user and password.											 		
	$request = $parserObj->ParseRequest($merchantObj, $request_assoc_array);
								
	//Submit the transaction request to the payment server
	$response = $parserObj->SendTransaction($merchantObj,$request);
	
	//Parse the response
	$parsed_array = $new_api_lib->parse_from_nvp($response);								 

	//Store the successIndicator for later use in the receipt page or receipt function.
	$successIndicator = $parsed_array['successIndicator'];

//The session ID is passed to the Checkout.configure() function below.
	$session_id = $parsed_array['session.id'];

//Store the variables in the session, or a database could be used for example
$_SESSION['successIndicator']= $successIndicator;
$_SESSION['orderID']= $order_id;
$_SESSION['orderReference']= $order_reference;
 
  $merchantID = "'" . $merchantObj->GetMerchantId() . "'";
};

?>

<head> 

   <script src="https://xxxxxx.gateway.xxxx.com/checkout/version/40/checkout.js"
   
           	 data-error="errorCallback"
           	 data-cancel="cancelCallback"
             data-complete="http://xxx.com/HOSTEDCheckout_Coding/Receipt_NVP.php"
            >
   </script>

   <script type="text/javascript">
        function errorCallback(error) {
              alert(JSON.stringify(error));
        }
        
        function completeCallback(resultIndicator, sessionVersion) {
              alert("Result Indicator");
			  				alert(JSON.stringify(resultIndicator));
              alert("Session Version:");
			  				alert(JSON.stringify(sessionVersion));
			  				alert("Successful Payment");
        }
       
        function cancelCallback() {
              alert('Payment cancelled');
        
        }
   
   
					Checkout.configure({
					merchant   : <?php echo $merchantID; ?>,
					order      : {
    				amount     : <?php echo json_encode($order_amount); ?>,
    				currency   : <?php echo json_encode($order_currency); ?>,
    				description: 'Happy Store Online',
    				id				 : <?php echo json_encode($order_id); ?>,
					reference				 : <?php echo json_encode($order_reference); ?>,
    				item			 : {
    					brand: 'xxx',
    					description: 'Happy Store Online',
    					name: 'HostedCheckoutItem',
    					quantity: '1',
    					unitPrice: '1.00',
    					unitTaxAmount: '1.00'
    				}
        	},
					billing    : {
						address  : {
							street: '300 Adelaide Street',
							stateProvince: 'QLD',
							city: 'Brisbane',
							company: 'Mastercard Pty Ltd',		
							postcodeZip: '4000',
							country: 'AUS'
						}
					},
					customer :{
						email: <?php echo $customer_receipt_email; ?>
				  },
					interaction: {
    				merchant: {
        		name: 'Happy Store Online',
        			address: {
        				line1: '300 Adelaide Street',
        				line2: 'Brisbane Queensland 4000'
    					},
    					  //logo:  'https://www.albemarle-london.com/OnlineBooking/Albemarle/ShowPics/ALBAniv.png'
    				}
					},
					session: { 
        			id: <?php echo json_encode($session_id); ?>
   						}
					});
					
    </script>

</head>

<body>
What happened is during sandbox, the source code worked with trial test credentials and we we naturally swapped it with production credentials and the whole checkout stopped at one time password (OTP). When we inserted the OTP into the checkout page, we expected the transaction to be successful but it wasnt.

Ended up we went back to the page filling in card details.

We checked with the bank and found out that the reference id didnt appear in the merchant administration. Hence the failure to conclude the transaction successfully.

Thanks for your help.

Bob

**Comment by marcoblos** [comment]
@foreigntalent sorry but I'm not employee at MasterCard company, I'm just a developer that try to smoothing things for me and for other that want to call the MasterCard Payment Gateway using Java.

Are you using PHP, right?
In Mastercard's GitHub has a lot of stuffs that you can meet it here: https://github.com/Mastercard and maybe this mastercard core php sdk can help you https://github.com/Mastercard/sdk-core-php

**Comment by foreigntalent** [comment]
Dear Marco,

I appreciate your help in pointing out the right direction nevertheless to me. We are still puzzle as to why the transaction couldn’t go through. 

Will try to reference from your link later.

Have a great day.

Bob

Sent from thy iPhone

**Comment by marcoblos** [comment]
Hi Bob. Sorry for the long 8 days delay in my last answer.

Where I work we get a lot of issues with this mastercard gateway too and we don't use this in production because the mastercard support with us is slow and the way to get this work done is not so docummented, IMHO.

I hope you can solve your problem with them, because at my enterprise so far we can't solve.

**Comment by foreigntalent** [comment]
Thanks Marco, 

MiGS worked but MPGS sucks.

Bob

Sent from thy iPhone
